# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - position_trajectory_controller

  position_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_1-2
      - shoulder_2-3
      - shoulder_3-upper
      - upper-elbow
      - elbow-lower
    action_ns: follow_joint_trajectory
    default: true